// AUTO-GENERATED by scripts/generate-products.py - NO EDITAR A MANO.
// Fuente: "EL GROW DE AIXA - LISTA DE PRECIOS.xls"
// Regenerar: python scripts/generate-products.py

export type CategoryId =
  | "sustratos"
  | "fertilizantes"
  | "control-plagas"
  | "macetas"
  | "accesorios"

export interface Product {
  id: string
  name: string
  category: CategoryId
  subcategory?: string
  brand?: string
  price: number | null
  salePrice?: number | null
  onSale: boolean
  inStock: boolean
  image?: string
  needsReview?: boolean
}

export interface CategoryMeta {
  id: CategoryId
  label: string
  shortLabel: string
  icon: string
  fallbackEmoji: string
  blurb: string
}

export const CATEGORIES: CategoryMeta[] = [
  { id: "sustratos", label: "Sustratos y Enmiendas", shortLabel: "Sustratos", icon: "Sprout", fallbackEmoji: "🌱", blurb: "Tierras, sustratos y enmiendas organicas para todas tus plantas." },
  { id: "fertilizantes", label: "Fertilizantes", shortLabel: "Fertilizantes", icon: "FlaskConical", fallbackEmoji: "🧪", blurb: "Nutrientes y fertilizantes para jardin y cultivo de cannabis." },
  { id: "control-plagas", label: "Control de Plagas", shortLabel: "Control de Plagas", icon: "Bug", fallbackEmoji: "🐛", blurb: "Insecticidas y fungicidas organicos para proteger tu cultivo." },
  { id: "macetas", label: "Macetas", shortLabel: "Macetas", icon: "Container", fallbackEmoji: "🪴", blurb: "Macetas y contenedores para cada etapa de crecimiento." },
  { id: "accesorios", label: "Accesorios", shortLabel: "Accesorios", icon: "Wrench", fallbackEmoji: "🧰", blurb: "Bandejas germinadoras, pulverizadores y mas." },
]

export const PRODUCTS: Product[] = [
  { id: "tierra-fertil-con-perlitas-x-5-dm", name: "Tierra Fertil con Perlitas x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 3000, onSale: false, inStock: true, image: "/products/tierra-fertil-con-perlitas-x-5-dm.jpg" },
  { id: "tierra-fertil-con-perlitas-x-25-dm", name: "Tierra Fertil con Perlitas x 25 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 12000, onSale: false, inStock: true, image: "/products/tierra-fertil-con-perlitas-x-25-dm.jpg" },
  { id: "tierra-fertil-con-perlitas-x-50-dm", name: "Tierra Fertil con Perlitas x 50 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 18000, onSale: false, inStock: true, image: "/products/tierra-fertil-con-perlitas-x-50-dm.jpg" },
  { id: "compost-organico-x-5-dm", name: "Compost Organico x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 4000, salePrice: 3000, onSale: true, inStock: true, image: "/products/compost-organico-x-5-dm.jpg" },
  { id: "compost-organico-x-25-dm", name: "Compost Organico x 25 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/compost-organico-x-25-dm.jpg" },
  { id: "humus-de-lombriz-x-2-dm", name: "Humus de Lombriz x 2 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 3000, onSale: false, inStock: true, image: "/products/humus-de-lombriz-x-2-dm.png" },
  { id: "humus-de-lombriz-x-5-dm", name: "Humus de Lombriz x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 5000, onSale: false, inStock: true, image: "/products/humus-de-lombriz-x-5-dm.png" },
  { id: "humus-de-lombriz-x-25-dm", name: "Humus de Lombriz x 25 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 17000, onSale: false, inStock: true, image: "/products/humus-de-lombriz-x-25-dm.png" },
  { id: "humus-de-lombriz-x-50-dm", name: "Humus de Lombriz x 50 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 28000, onSale: false, inStock: true, image: "/products/humus-de-lombriz-x-50-dm.png" },
  { id: "turba-rubia-x-2-dm", name: "Turba Rubia x 2 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/turba-rubia-x-2-dm.webp" },
  { id: "turba-rubia-x-5-dm", name: "Turba Rubia x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 8000, onSale: false, inStock: true, image: "/products/turba-rubia-x-5-dm.webp" },
  { id: "musgo-sphagnum-x-2-dm", name: "Musgo Sphagnum x 2 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/musgo-sphagnum-x-2-dm.webp" },
  { id: "corteza-de-pino-x-5-dm", name: "Corteza de Pino x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 5000, onSale: false, inStock: true, image: "/products/corteza-de-pino-x-5-dm.webp" },
  { id: "corteza-de-pino-x-25-dm", name: "Corteza de Pino x 25 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: null, onSale: false, inStock: true, image: "/products/corteza-de-pino-x-25-dm.webp" },
  { id: "corteza-de-pino-x-50-dm", name: "Corteza de Pino x 50 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/corteza-de-pino-x-50-dm.webp" },
  { id: "sustrato-para-cactus-y-suculentas-x-5-dm", name: "Sustrato para Cactus y Suculentas x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 4000, onSale: false, inStock: true, image: "/products/sustrato-para-cactus-y-suculentas-x-5-dm.jpg" },
  { id: "sustrato-para-cactus-y-suculentas-x-25-dm", name: "Sustrato para Cactus y Suculentas x 25 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 14000, onSale: false, inStock: true, image: "/products/sustrato-para-cactus-y-suculentas-x-25-dm.jpg" },
  { id: "sustrato-para-bonsai-x-5-dm", name: "Sustrato para Bonsai x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 6000, onSale: false, inStock: true, image: "/products/sustrato-para-bonsai-x-5-dm.jpg" },
  { id: "sustrato-para-orquideas-x-5-dm", name: "Sustrato para Orquideas x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 6000, onSale: false, inStock: true, image: "/products/sustrato-para-orquideas-x-5-dm.webp" },
  { id: "sustrato-ph5-plantas-acidofilas-x-5-dm", name: "Sustrato PH5 - Plantas Acidofilas - x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 6000, onSale: false, inStock: true, image: "/products/sustrato-ph5-plantas-acidofilas-x-5-dm.png" },
  { id: "perlita-agricola-x-5-dm", name: "Perlita Agricola x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 4000, onSale: false, inStock: true, image: "/products/perlita-agricola-x-5-dm.webp" },
  { id: "perlita-agricola-x-125-dm", name: "Perlita Agricola x 125 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 30000, onSale: false, inStock: true, image: "/products/perlita-agricola-x-125-dm.webp" },
  { id: "vermiculita-x-2-dm", name: "Vermiculita x 2 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 6000, salePrice: 5000, onSale: true, inStock: true, image: "/products/vermiculita-x-2-dm.webp" },
  { id: "cascarilla-de-arroz-x-5-dm", name: "Cascarilla de Arroz x 5 dm", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 7000, salePrice: 6000, onSale: true, inStock: true, image: "/products/cascarilla-de-arroz-x-5-dm.jpg" },
  { id: "tierra-de-diatomeas-fertilizante-x-500-gr", name: "Tierra de Diatomeas Fertilizante x 500 gr", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 4500, onSale: false, inStock: true, image: "/products/tierra-de-diatomeas-fertilizante-x-500-gr.webp" },
  { id: "tierra-de-diatomeas-fertilizante-x-1-kilo", name: "Tierra de Diatomeas Fertilizante x 1 kilo", category: "sustratos", subcategory: "Enmiendas Organicas", brand: "Compostuc", price: 9000, onSale: false, inStock: true, image: "/products/tierra-de-diatomeas-fertilizante-x-1-kilo.webp" },
  { id: "sustrato-universal-x-25-dm", name: "Sustrato Universal x 25 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: 24000, onSale: false, inStock: true, image: "/products/sustrato-universal-x-25-dm.jpg" },
  { id: "sustrato-universal-x-50-dm", name: "Sustrato Universal x 50 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: 30000, onSale: false, inStock: true, image: "/products/sustrato-universal-x-50-dm.jpg" },
  { id: "living-soil-x-20-dm", name: "Living Soil x 20 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: 24000, salePrice: 18000, onSale: true, inStock: true, image: "/products/living-soil-x-20-dm.jpg" },
  { id: "living-soil-x-50-dm", name: "Living Soil x 50 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/living-soil-x-50-dm.jpg" },
  { id: "profesional-grow-x-20-dm", name: "Profesional Grow X 20 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/profesional-grow-x-20-dm.jpg" },
  { id: "profesional-grow-x-70-dm", name: "Profesional Grow X 70 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/profesional-grow-x-70-dm.jpg" },
  { id: "light-mix-indoor-x-20-dm", name: "Light Mix (Indoor) x 20 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/light-mix-indoor-x-20-dm.webp" },
  { id: "light-mix-indoor-x-70-dm", name: "Light Mix (Indoor) x 70 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/light-mix-indoor-x-70-dm.webp" },
  { id: "all-mix-outdoor-x-20-dm", name: "All Mix (Outdoor) x 20 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/all-mix-outdoor-x-20-dm.jpg" },
  { id: "all-mix-outdoor-x-70-dm", name: "All Mix (Outdoor) x 70 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/all-mix-outdoor-x-70-dm.jpg" },
  { id: "auto-mix-x-20-dm", name: "Auto Mix x 20 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/auto-mix-x-20-dm.jpg" },
  { id: "auto-mix-x-70-dm", name: "Auto Mix x 70 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/auto-mix-x-70-dm.jpg" },
  { id: "super-mix-x-20-dm", name: "Super Mix x 20 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/super-mix-x-20-dm.jpg" },
  { id: "super-mix-x-80-dm", name: "Super Mix x 80 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: false, image: "/products/super-mix-x-80-dm.jpg" },
  { id: "fibra-de-coco-x-5-dm", name: "Fibra de Coco x 5 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: 8000, onSale: false, inStock: true, image: "/products/fibra-de-coco-x-5-dm.jpg" },
  { id: "fibra-de-coco-x-20-dm", name: "Fibra de Coco x 20 dm", category: "sustratos", subcategory: "Sustratos Cannabis", brand: "Compostuc", price: null, onSale: false, inStock: true, image: "/products/fibra-de-coco-x-20-dm.jpg" },
  { id: "growmix-multipro-x-20-dm", name: "GrowMix MultiPro x 20 dm", category: "sustratos", brand: "GrowMix", price: null, onSale: false, inStock: false, image: "/products/growmix-multipro-x-20-dm.jpg" },
  { id: "growmix-multipro-x-80-dm", name: "GrowMix MultiPro x 80 dm", category: "sustratos", brand: "GrowMix", price: 50000, onSale: false, inStock: true, image: "/products/growmix-multipro-x-80-dm.jpg" },
  { id: "growmix-premium-x-80-dm", name: "GrowMix Premium x 80 dm", category: "sustratos", brand: "GrowMix", price: null, onSale: false, inStock: false, image: "/products/growmix-premium-x-80-dm.jpg" },
  { id: "cultivate-completo-x-25-dm", name: "Cultivate Completo x 25 dm", category: "sustratos", brand: "Cultivate", price: 23000, onSale: false, inStock: true, image: "/products/cultivate-completo-x-25-dm.webp" },
  { id: "cultivate-completo-x-80-dm", name: "Cultivate Completo x 80 dm", category: "sustratos", brand: "Cultivate", price: null, onSale: false, inStock: false, image: "/products/cultivate-completo-x-80-dm.webp" },
  { id: "cultivate-premium-x-25-dm", name: "Cultivate Premium x 25 dm", category: "sustratos", brand: "Cultivate", price: null, onSale: false, inStock: false, image: "/products/cultivate-premium-x-25-dm.jpg" },
  { id: "cultivate-premium-x-80-dm", name: "Cultivate Premium x 80 dm", category: "sustratos", brand: "Cultivate", price: null, onSale: false, inStock: false, image: "/products/cultivate-premium-x-80-dm.jpg" },
  { id: "vitaflor-light-mix-x-50-dm", name: "VitaFlor Light Mix x 50 dm", category: "sustratos", brand: "VitaFlor", price: null, onSale: false, inStock: false, image: "/products/vitaflor-light-mix-x-50-dm.png" },
  { id: "vitaflor-all-mix-x-50-dm", name: "VitaFlor All Mix x 50 dm", category: "sustratos", brand: "VitaFlor", price: 36000, onSale: false, inStock: true, image: "/products/vitaflor-all-mix-x-50-dm.png" },
  { id: "enraizante-x-250-cc", name: "Enraizante x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 7000, onSale: false, inStock: true, image: "/products/enraizante-x-250-cc.png" },
  { id: "follaje-x-250-cc", name: "Follaje x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 7000, onSale: false, inStock: true, image: "/products/follaje-x-250-cc.png" },
  { id: "floracion-x-250-cc", name: "Floracion x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 7000, onSale: false, inStock: true, image: "/products/floracion-x-250-cc.jpg" },
  { id: "orquideas-x-250-cc", name: "Orquideas x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 7000, onSale: false, inStock: true, image: "/products/orquideas-x-250-cc.jpg" },
  { id: "bonsai-x-250-cc", name: "Bonsai x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: null, onSale: false, inStock: false, image: "/products/bonsai-x-250-cc.webp" },
  { id: "helechos-x-250-cc", name: "Helechos x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: null, onSale: false, inStock: false, image: "/products/helechos-x-250-cc.jpg" },
  { id: "cesped-x-500-cc", name: "Cesped x 500  cc", category: "fertilizantes", subcategory: "Linea Jardin", price: null, onSale: false, inStock: false, image: "/products/cesped-x-500-cc.webp" },
  { id: "para-cactus-y-suculentas-x-500-cc", name: "Para Cactus y Suculentas x 500 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 10000, onSale: false, inStock: true, image: "/products/para-cactus-y-suculentas-x-500-cc.webp", needsReview: true },
  { id: "humus-de-lombriz-x-500-cc", name: "Humus de Lombriz x 500 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 5000, onSale: false, inStock: true, image: "/products/humus-de-lombriz-x-500-cc.png" },
  { id: "humus-de-lombriz-x-1-ltr", name: "Humus de Lombriz x 1 ltr", category: "fertilizantes", subcategory: "Linea Jardin", price: 7000, onSale: false, inStock: true, image: "/products/humus-de-lombriz-x-1-ltr.png" },
  { id: "humus-de-lombriz-x-5-ltr", name: "Humus de Lombriz x 5 ltr", category: "fertilizantes", subcategory: "Linea Jardin", price: 18000, onSale: false, inStock: true, image: "/products/humus-de-lombriz-x-5-ltr.png" },
  { id: "guano-de-gallina-x-250-cc", name: "Guano de Gallina x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 6000, salePrice: 4000, onSale: true, inStock: true, image: "/products/guano-de-gallina-x-250-cc.webp" },
  { id: "guano-de-murcielago-x-250-cc", name: "Guano de Murcielago x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 9000, salePrice: 6000, onSale: true, inStock: true, image: "/products/guano-de-murcielago-x-250-cc.jpg" },
  { id: "harina-de-sangre-x-250-cc", name: "Harina de Sangre x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 7000, salePrice: 5000, onSale: true, inStock: true, image: "/products/harina-de-sangre-x-250-cc.jpg" },
  { id: "harina-de-hueso-x-250-cc", name: "Harina de Hueso x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 7000, salePrice: 5000, onSale: true, inStock: true, image: "/products/harina-de-hueso-x-250-cc.png" },
  { id: "harina-de-rocas-x-250-cc", name: "Harina de Rocas x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 8000, salePrice: 5000, onSale: true, inStock: true, image: "/products/harina-de-rocas-x-250-cc.png" },
  { id: "dolomita-x-125-cc", name: "Dolomita x 125 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 5000, onSale: false, inStock: true, image: "/products/dolomita-x-125-cc.webp" },
  { id: "sales-de-epsom-x-250-cc", name: "Sales de Epsom x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 6000, salePrice: 4000, onSale: true, inStock: true, image: "/products/sales-de-epsom-x-250-cc.png" },
  { id: "sulfato-de-hierro-x-250-cc", name: "Sulfato de Hierro x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 5000, onSale: false, inStock: true, image: "/products/sulfato-de-hierro-x-250-cc.webp" },
  { id: "nutripack-raices-pellets-x-250-cc", name: "NutriPack Raices - (Pellets) - x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 6000, salePrice: 4000, onSale: true, inStock: true, image: "/products/nutripack-raices-pellets-x-250-cc.jpg" },
  { id: "nutripack-vegetacion-pellets-x-250-cc", name: "NutriPack Vegetacion - (Pellets) - x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 6000, salePrice: 4000, onSale: true, inStock: true, image: "/products/nutripack-vegetacion-pellets-x-250-cc.jpg" },
  { id: "nutripack-floracion-pellets-x-250-cc", name: "NutriPack Floracion - (Pellets) - x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 6000, salePrice: 4000, onSale: true, inStock: true, image: "/products/nutripack-floracion-pellets-x-250-cc.jpg" },
  { id: "mmn-microorg-de-montana-nativ-x-250-cc", name: "MMN - Microorg de Montaña Nativ x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 6000, onSale: false, inStock: true, image: "/products/mmn-microorg-de-montana-nativ-x-250-cc.png" },
  { id: "perlhumus-x-250-cc", name: "PerlHumus x 250 cc", category: "fertilizantes", subcategory: "Linea Jardin", price: 5000, onSale: false, inStock: true, image: "/products/perlhumus-x-250-cc.png" },
  { id: "max-roots-x-150-cc", name: "Max Roots x 150 cc", category: "fertilizantes", subcategory: "Linea Cannabis", brand: "Weed Breeders", price: 8000, onSale: false, inStock: true, image: "/products/max-roots-x-150-cc.jpg" },
  { id: "max-green-x-250-cc", name: "Max Green x 250 cc", category: "fertilizantes", subcategory: "Linea Cannabis", brand: "Weed Breeders", price: 8000, onSale: false, inStock: true, image: "/products/max-green-x-250-cc.jpg" },
  { id: "max-vege-x-250-cc", name: "Max Vege x 250 cc", category: "fertilizantes", subcategory: "Linea Cannabis", brand: "Weed Breeders", price: 8000, onSale: false, inStock: true, image: "/products/max-vege-x-250-cc.jpg" },
  { id: "max-flora-x-250-cc", name: "Max Flora x 250 cc", category: "fertilizantes", subcategory: "Linea Cannabis", brand: "Weed Breeders", price: 8000, onSale: false, inStock: true, image: "/products/max-flora-x-250-cc.jpg" },
  { id: "max-sweet-x-250-cc", name: "Max Sweet x 250 cc", category: "fertilizantes", subcategory: "Linea Cannabis", brand: "Weed Breeders", price: 8000, onSale: false, inStock: true, image: "/products/max-sweet-x-250-cc.jpg" },
  { id: "mad-bud-x-250-cc", name: "Mad Bud x 250 cc", category: "fertilizantes", subcategory: "Linea Cannabis", brand: "Weed Breeders", price: 8000, onSale: false, inStock: true, image: "/products/mad-bud-x-250-cc.jpg" },
  { id: "max-bio-x-250-cc", name: "Max Bio x 250 cc", category: "fertilizantes", subcategory: "Linea Cannabis", brand: "Weed Breeders", price: 8000, onSale: false, inStock: true, image: "/products/max-bio-x-250-cc.jpg" },
  { id: "nutripack-x-5", name: "Nutripack x 5", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/nutripack-x-5.png" },
  { id: "amazonia-x-150-gr-enraizante", name: "Amazonia x 150 gr (Enraizante)", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/amazonia-x-150-gr-enraizante.png" },
  { id: "amazonia-x-300-gr", name: "Amazonia x 300 gr", category: "fertilizantes", brand: "Namaste", price: 35000, onSale: false, inStock: true, image: "/products/amazonia-x-300-gr.png" },
  { id: "oro-negro-x-100-ml-vegetativo", name: "Oro Negro x 100 ml (Vegetativo)", category: "fertilizantes", brand: "Namaste", price: 7000, onSale: false, inStock: true, image: "/products/oro-negro-x-100-ml-vegetativo.webp" },
  { id: "oro-negro-x-500-ml", name: "Oro Negro x 500 ml", category: "fertilizantes", brand: "Namaste", price: 20000, onSale: false, inStock: true, image: "/products/oro-negro-x-500-ml.webp" },
  { id: "oro-negro-x-2-ltr", name: "Oro Negro x 2 ltr", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/oro-negro-x-2-ltr.webp" },
  { id: "flora-booster-x-100-ml-floracion", name: "Flora Booster x 100 ml (Floracion)", category: "fertilizantes", brand: "Namaste", price: 7000, onSale: false, inStock: true, image: "/products/flora-booster-x-100-ml-floracion.webp" },
  { id: "flora-booster-x-500-ml", name: "Flora Booster x 500 ml", category: "fertilizantes", brand: "Namaste", price: 20000, onSale: false, inStock: true, image: "/products/flora-booster-x-500-ml.webp" },
  { id: "flora-booster-x-2-ltr", name: "Flora Booster x 2 ltr", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/flora-booster-x-2-ltr.webp" },
  { id: "trico-x100-gr-floracion", name: "Trico + x100 gr (Floracion)", category: "fertilizantes", brand: "Namaste", price: 9000, onSale: false, inStock: true, image: "/products/trico-x100-gr-floracion.webp" },
  { id: "trico-x-250-gr", name: "Trico + x 250 gr", category: "fertilizantes", brand: "Namaste", price: 16000, onSale: false, inStock: true, image: "/products/trico-x-250-gr.webp" },
  { id: "trico-x-1100-gr", name: "Trico + x 1100 gr", category: "fertilizantes", brand: "Namaste", price: 45000, onSale: false, inStock: true, image: "/products/trico-x-1100-gr.webp" },
  { id: "shanti-x-100-ml-bioestimulante", name: "Shanti x 100 ml (Bioestimulante)", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/shanti-x-100-ml-bioestimulante.jpeg" },
  { id: "ph-x-100-ml", name: "PH - X 100 ml", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/ph-x-100-ml.webp" },
  { id: "ph-x-500-ml", name: "PH - X 500 ml", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/ph-x-500-ml.webp" },
  { id: "ph-x-2-ltr", name: "PH - X 2 ltr", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/ph-x-2-ltr.webp" },
  { id: "detox-x-500-ml", name: "Detox x 500 ml", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/detox-x-500-ml.webp" },
  { id: "detox-x-2-ltr", name: "Detox x 2 ltr", category: "fertilizantes", brand: "Namaste", price: 35000, onSale: false, inStock: true, image: "/products/detox-x-2-ltr.webp" },
  { id: "bioprotect-x-100-ml", name: "BioProtect x 100 ml", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/bioprotect-x-100-ml.webp" },
  { id: "bioneem-x-30-ml", name: "BioNeem x 30 ml", category: "fertilizantes", brand: "Namaste", price: null, onSale: false, inStock: false, image: "/products/bioneem-x-30-ml.png" },
  { id: "tripack-deeper-vege-bloom", name: "TriPack (Deeper, Vege, Bloom)", category: "fertilizantes", brand: "Top Crop", price: null, onSale: false, inStock: false, image: "/products/tripack-deeper-vege-bloom.png" },
  { id: "deeper-x-100-ml-enraizante", name: "Deeper x 100 ml (Enraizante)", category: "fertilizantes", brand: "Top Crop", price: 7000, onSale: false, inStock: true, image: "/products/deeper-x-100-ml-enraizante.jpg" },
  { id: "deeper-x-250-ml", name: "Deeper x 250 ml", category: "fertilizantes", brand: "Top Crop", price: 13000, onSale: false, inStock: true, image: "/products/deeper-x-250-ml.jpg" },
  { id: "top-vege-x-250-ml-vegetativo", name: "Top Vege x 250 ml (Vegetativo)", category: "fertilizantes", brand: "Top Crop", price: 10000, onSale: false, inStock: true, image: "/products/top-vege-x-250-ml-vegetativo.jpg" },
  { id: "top-vege-x-1-ltr", name: "Top Vege x 1 ltr", category: "fertilizantes", brand: "Top Crop", price: 40000, onSale: false, inStock: true, image: "/products/top-vege-x-1-ltr.jpg" },
  { id: "top-candy-x-250-floracion", name: "Top Candy x 250 (Floracion)", category: "fertilizantes", brand: "Top Crop", price: 12000, onSale: false, inStock: true, image: "/products/top-candy-x-250-floracion.webp" },
  { id: "top-candy-x-1-ltr", name: "Top Candy x 1 ltr", category: "fertilizantes", brand: "Top Crop", price: 35000, onSale: false, inStock: true, image: "/products/top-candy-x-1-ltr.webp", needsReview: true },
  { id: "top-bloom-x-250-ml-floracion", name: "Top Bloom x 250 ml (Floracion)", category: "fertilizantes", brand: "Top Crop", price: 12000, onSale: false, inStock: true, image: "/products/top-bloom-x-250-ml-floracion.jpg" },
  { id: "top-bloom-x-1-ltr", name: "Top Bloom x 1 ltr", category: "fertilizantes", brand: "Top Crop", price: 40000, onSale: false, inStock: true, image: "/products/top-bloom-x-1-ltr.jpg" },
  { id: "top-auto-x-250-ml", name: "Top Auto x 250 ml", category: "fertilizantes", brand: "Top Crop", price: 13000, onSale: false, inStock: true, image: "/products/top-auto-x-250-ml.webp", needsReview: true },
  { id: "top-barrier-x-100-ml", name: "Top Barrier x 100 ml", category: "fertilizantes", brand: "Top Crop", price: null, onSale: false, inStock: false, image: "/products/top-barrier-x-100-ml.webp" },
  { id: "top-barrier-x-250-ml", name: "Top Barrier x 250 ml", category: "fertilizantes", brand: "Top Crop", price: 15000, onSale: false, inStock: true, image: "/products/top-barrier-x-250-ml.webp" },
  { id: "bokashi-vegetativo-x-800-cm", name: "Bokashi Vegetativo x 800 cm", category: "fertilizantes", brand: "Vamp", price: null, onSale: false, inStock: false, image: "/products/bokashi-vegetativo-x-800-cm.png" },
  { id: "bokashi-gallina-murcielago-x-800-cm", name: "Bokashi Gallina + Murcielago x 800 cm", category: "fertilizantes", brand: "Vamp", price: null, onSale: false, inStock: false, image: "/products/bokashi-gallina-murcielago-x-800-cm.webp" },
  { id: "bokashi-flora-x-800-cm", name: "Bokashi Flora x 800 cm", category: "fertilizantes", brand: "Vamp", price: null, onSale: false, inStock: false, image: "/products/bokashi-flora-x-800-cm.jpg" },
  { id: "bokashi-gallina-murcielago-x-800-cm-2", name: "Bokashi Gallina + Murcielago x 800 cm", category: "fertilizantes", brand: "Vamp", price: null, onSale: false, inStock: false, image: "/products/bokashi-gallina-murcielago-x-800-cm-2.webp" },
  { id: "maca-brew-x-500-ml", name: "Maca Brew x 500 ml", category: "fertilizantes", brand: "Maca Brew", price: 4000, onSale: false, inStock: true, image: "/products/maca-brew-x-500-ml.jpg" },
  { id: "maca-brew-x-1-ltr", name: "Maca Brew x 1 ltr", category: "fertilizantes", brand: "Maca Brew", price: 8000, onSale: false, inStock: true, image: "/products/maca-brew-x-1-ltr.jpg" },
  { id: "jabon-potasico-con-neem-y-canela-x-200-cc", name: "Jabon Potasico con Neem y Canela x 200 cc", category: "control-plagas", subcategory: "Control de Plagas", price: 10000, onSale: false, inStock: true, image: "/products/jabon-potasico-con-neem-y-canela-x-200-cc.jpg" },
  { id: "em-5-insecticida-y-fungicida-organico-x-250-cc", name: "EM 5 (Insecticida y fungicida organico) x 250 cc", category: "control-plagas", subcategory: "Control de Plagas", price: 6000, onSale: false, inStock: true, image: "/products/em-5-insecticida-y-fungicida-organico-x-250-cc.webp" },
  { id: "killer-x-250-cc", name: "Killer x 250 cc", category: "control-plagas", subcategory: "Control de Plagas", price: 6000, onSale: false, inStock: true, image: "/products/killer-x-250-cc.webp" },
  { id: "miko-micorrizas-en-polvo-x-33-grs", name: "Miko (Micorrizas en polvo) x 33 grs", category: "control-plagas", subcategory: "Control de Plagas", price: 8000, onSale: false, inStock: true, image: "/products/miko-micorrizas-en-polvo-x-33-grs.jpg" },
  { id: "triko-trichodermas-en-polvo-x-33-grs", name: "Triko (Trichodermas en polvo) x 33 grs", category: "control-plagas", subcategory: "Control de Plagas", price: 8000, onSale: false, inStock: true, image: "/products/triko-trichodermas-en-polvo-x-33-grs.jpg" },
  { id: "tierra-de-diatomeas-insecticida-x-1-kilo", name: "Tierra de Diatomeas Insecticida x 1 kilo", category: "control-plagas", subcategory: "Control de Plagas", price: 9000, onSale: false, inStock: true, image: "/products/tierra-de-diatomeas-insecticida-x-1-kilo.jpg" },
  { id: "mad-rocket-x-5-ltrs", name: "Mad Rocket x 5 ltrs", category: "macetas", brand: "Mad Rocket", price: null, onSale: false, inStock: true, image: "/products/mad-rocket-x-5-ltrs.jpg" },
  { id: "mad-rocket-x-10-ltrs", name: "Mad Rocket x 10 ltrs", category: "macetas", brand: "Mad Rocket", price: null, onSale: false, inStock: true, image: "/products/mad-rocket-x-10-ltrs.jpg" },
  { id: "mad-rocket-x-16-ltrs", name: "Mad Rocket x 16 ltrs", category: "macetas", brand: "Mad Rocket", price: null, onSale: false, inStock: true, image: "/products/mad-rocket-x-16-ltrs.jpg" },
  { id: "mad-rocket-x-25-ltrs", name: "Mad Rocket x 25 ltrs", category: "macetas", brand: "Mad Rocket", price: null, onSale: false, inStock: true, image: "/products/mad-rocket-x-25-ltrs.jpg" },
  { id: "roots-house-x-35-ltrs", name: "Roots House x 35 ltrs", category: "macetas", brand: "Roots House", price: null, onSale: false, inStock: true, image: "/products/roots-house-x-35-ltrs.webp" },
  { id: "n-10-400-ml", name: "Nº 10 (400 ml)", category: "macetas", subcategory: "Negras Sopladas", price: 100, onSale: false, inStock: true, image: "/products/n-10-400-ml.jpg" },
  { id: "n-12-750-ml", name: "Nº 12 (750 ml)", category: "macetas", subcategory: "Negras Sopladas", price: 200, onSale: false, inStock: true, image: "/products/n-12-750-ml.jpg" },
  { id: "n-14-1-5-ltrs", name: "Nº 14 (1,5 ltrs)", category: "macetas", subcategory: "Negras Sopladas", price: 300, onSale: false, inStock: true, image: "/products/n-14-1-5-ltrs.webp" },
  { id: "n-16-3-ltrs", name: "Nº 16 (3 ltrs)", category: "macetas", subcategory: "Negras Sopladas", price: 500, onSale: false, inStock: true, image: "/products/n-16-3-ltrs.webp" },
  { id: "n-20-5-ltrs", name: "Nº 20 (5 ltrs)", category: "macetas", subcategory: "Negras Sopladas", price: null, onSale: false, inStock: false, image: "/products/n-20-5-ltrs.jpg" },
  { id: "n-7-ltrs", name: "Nº (7 ltrs)", category: "macetas", subcategory: "Negras Sopladas", price: null, onSale: false, inStock: false, image: "/products/n-7-ltrs.webp" },
  { id: "n-22-10-ltrs", name: "Nº 22 (10 ltrs)", category: "macetas", subcategory: "Negras Sopladas", price: 2000, onSale: false, inStock: true, image: "/products/n-22-10-ltrs.jpg" },
  { id: "n-15-ltrs", name: "Nº 15 ltrs", category: "macetas", subcategory: "Negras Sopladas", price: 4000, onSale: false, inStock: true, image: "/products/n-15-ltrs.jpg" },
  { id: "n-20-ltrs", name: "Nº 20 ltrs", category: "macetas", subcategory: "Negras Sopladas", price: null, onSale: false, inStock: false, image: "/products/n-20-ltrs.webp" },
  { id: "n-128-celdas", name: "Nº 128 celdas", category: "accesorios", subcategory: "Bandejas Germinadoras", price: 3000, onSale: false, inStock: true, image: "/products/n-128-celdas.jpg" },
  { id: "x-1-ltr", name: "X 1 ltr", category: "accesorios", subcategory: "Pulverizadores", brand: "Calplot", price: null, onSale: false, inStock: true, image: "/products/x-1-ltr.webp" },
  { id: "x-2-ltrs", name: "X 2 ltrs", category: "accesorios", subcategory: "Pulverizadores", brand: "Calplot", price: null, onSale: false, inStock: true, image: "/products/x-2-ltrs.jpg" },
  { id: "x-5-ltrs", name: "X 5 ltrs", category: "accesorios", subcategory: "Pulverizadores", brand: "Calplot", price: null, onSale: false, inStock: true, image: "/products/x-5-ltrs.jpg" },
]

export function getCategory(id: CategoryId): CategoryMeta | undefined {
  return CATEGORIES.find((c) => c.id === id)
}

export function getProductsByCategory(id: CategoryId): Product[] {
  return PRODUCTS.filter((p) => p.category === id)
}

function normalize(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
}

export function searchProducts(
  query: string,
  products: Product[] = PRODUCTS,
): Product[] {
  const q = normalize(query.trim())
  if (!q) return products
  return products.filter((p) =>
    normalize([p.name, p.brand ?? "", p.subcategory ?? ""].join(" ")).includes(q),
  )
}
